### ISSUE TITLE
Disallow unambiguous JsonPath

### ISSUE THREAD

**Issue by gavlyukovskiy** [Breus/json-masker#77]
With the introduction of wildcards, we want to disallow unambiguous JsonPath combinations. The main reason is to avoid loopbacks during matching that could occur for such combinations:
```
$.a.*.c
$.a.b.*
```
on a JSON
```json
{
  "a": {
    "b": {
      "d": "masked"
    }
  }
}
```

current implementation only matches forward, meaning that node "a.b" would be already matched against "a.*", but  the next node "d" would fail to match the first JsonPath while satisfying the second JsonPath, which would require a loopback.

Until someone asks for this particular use case, providing a good reason, we should not allow these.

**Comment by donavdey** [comment]
For the record, `$.a.b.c` and `$.a.*.d` combination is still ambiguous, even though query arguments are different.

**Comment by donavdey** [comment]
One more comment is that (`$.a.b.*`, `$.a.b.*.c`) and (`$.a.b.c`, `$.a.b.c.*`) combinations are not ambiguous as we can match forward.

**Comment by gavlyukovskiy** [comment]
> For the record, $.a.b.c and $.a.*.d combination is still ambiguous

yes, correct. We should also block those. Basically on every position it either has the concrete symbol or a wildcard\

> One more comment is that ($.a.b.*, $.a.b.*.c) and ($.a.b.c, $.a.b.c.*) combinations are not ambiguous as we can match forward.

Practically that doesn't mean anything - in both allow mode and mask mode - `$.a.b.*` already masks the whole object, so you don't have to overspecify that `c` needs to be masked. Not sure if we can block those easily, but I'd try to
