### ISSUE TITLE
Keys and JsonPATH keys are not isolated form each other in the trie

### ISSUE THREAD

**Issue by donavdey** [Breus/json-masker#94]
Given the following configuration
```
maskKeys: $.a
maskJsonPaths: $.b, $.c
```
And the following json:
```
{
  "a": "do not mask",
  "b": "mask",
  "c": "mask",
}
```
The result will be:
```
{
  "a": "***",
  "b": "***",
  "c": "***",
}
```
The expected result should be:
```
{
  "a": "do not mask",
  "b": "***",
  "c": "***",
}
```

The bug is caused by not separating keys and JsonPATH keys in the trie. This can be solved by either using a separate trie instance for JsonPATH keys or ascribing a type to the `endOfWord` field in trie nodes (`endOfJsonPathKeyWord` and `endOfKeyWord`)

**Comment by gavlyukovskiy** [comment]
I think we could live with that honestly, though having separate tries is also an option

**Comment by Breus** [comment]
I honestly don't see this ever becoming a real life problem, but I agree separate trees for normal target keys and JSON paths would be the preferred way to solve this.
